pipeline{
    agent any
    

    environment{
        def myString = "Hello"
        def myNumber = 20
        def myBool = true
                
    }

    stages{
        stage("Demo"){
            steps{
                echo "myString: ${myString}"
                echo "myNumber: ${myNumber}"
                echo "myBool: ${myBool}"

            }
        }
    }
}
